{% set name = "reno-sd" %}
{% set python_min = "3.11" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reno_sd-{{ version }}.tar.gz
  sha256: ce2feadc305dd32d5baa3a4058a60c6fe10720ed3b5213f8c65bb324a266b5a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - xarray
    - panel <1.8
    - pymc
    - matplotlib-base
    - selenium
    - ipyvuetify
    - python-graphviz

test:
  imports:
    - reno
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ORNL/reno
  summary: System dynamics modeling with bayesian inference
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ornl.github.io/reno/stable/index.html

extra:
  recipe-maintainers:
    - WarmCyan
